### ISSUE TITLE
Component doesn't work with dash 1.5+

### ISSUE THREAD

**Issue by bcliang** [bcliang/dash-extendable-graph#32]

**Comment by bcliang** [comment]
will plan to resolve this work while addressing #31

**Comment by matthijsramlab** [comment]
@bcliang do you have any idea when this will be fixed?  Am using the component since the beginning, and it is really nice!

**Comment by bcliang** [comment]
@matthijsramlab Sorry about that. I don't have usage stats on the component so I didn't realize anyone was using this. I have been busy with work, so this change has been slow coming. I hope to resolve this issue (and #31) by this weekend. 

I have a working version already that is based on how plotly/dash-core-components implements dynamic loading, but it actually also dynamically loads dash-extendable-graph as well which in retrospect I think was a mistake. Also, I think I broke some tests. 

See the changes in this branch: https://github.com/bcliang/dash-extendable-graph/tree/lazy-loading

**Comment by bcliang** [comment]
Component is now working with version 1.1.0. Async behavior wasn't added, and would likely be something pushed to 2.0. I left the branch up there for now.
