### ISSUE TITLE
Question about updateData

### ISSUE THREAD

**Issue by danielTobon43** [bcliang/dash-extendable-graph#39]
Hi, I am testing your code and is working with 'extendData' which is fine if I want to add more points to the same graph, my question is if there is a way that I could use your code to update the data instead of appending new data since I have been doing an "updating" in my graph each time creating a new figure which is time-consuming, so your code looks really good for what I want to do. So, to summarize, is there a way where I could use your code to just update a graph?

**Comment by bcliang** [comment]
Hi there. Unfortunately this is not supported at the moment, and not supported within the PlotlyJS, which is what this component is a wrapper for. In this component, extending trace data is achieved by calling PlotlyJS' built-in method `extendTraces.` In cases where it's a new trace we use the method `addTraces`. 

To perform a data update operation, there is no "updateTraces" method available in the library. I believe the approach that would need to be taken is:
1. Persist selected trace data in memory
2. Delete selected trace via [`deleteTraces`](https://plotly.com/javascript/plotlyjs-function-reference/#plotlydeletetraces) API
3. Add trace in the same position via [`addTraces`](https://plotly.com/javascript/plotlyjs-function-reference/#plotlyaddtraces) API

In the case of a single trace within the figure, this is equivalent to what you are doing right now (redrawing the entire figure each time). The above approach will be faster if you are only updating a single trace, though.

I'll think about how to support it. I think the use case is something that potentially would be useful to a lot of people. It may be easier to add a feature request to Plotly for something like adding a new`updateTraceData` or `replaceTraceData` method that can meet your use case. [plotly.js repo](https://github.com/plotly/plotly.js). You could also make the feature request directly to the [dash-core-components](https://github.com/plotly/dash-core-components).

**Comment by danielTobon43** [comment]
Hi, thanks for the reply answer.  I will try to follow your approach to see what happens, thanks!
