### ISSUE TITLE
Support for subplots

### ISSUE THREAD

**Issue by nsbruce** [bcliang/dash-extendable-graph#48]
When a figure contains subplots of the form

```
figure={
  'data': [
    {
      'name': 'spec',
      'type': 'line',
      'xaxis': 'x1',
      'yaxis': 'y1',
      'y': spec[0],
    },
    {
      'name': 'waterfall',
      'type': 'heatmap',
      'xaxis': 'x1',
      'yaxis': 'y2',
      'z': spec,
    }
  ]
  ```
  where `spec` is a 2D numpy array the data is not extensible. For the above example I want to use `extendData` to update the y-values of the first subplot and the z-values of the second subplot. The two subplots share an x-axis but I don't think that's relevant.
  
Passing `extendData` an array of these two dicts results in a wrong number of arguments error. Is this supported and I'm getting the syntax wrong?

**Comment by bcliang** [comment]
The component hasn't been explicitly tested for subplots of any type, but I think it should be supported?  I developed this with basic scatter plots in mind; tests were built around that use case.

Hopefully the following works, but if not I will try to take a look this weekend. Apologies ahead of time -- the component is not really a priority for me and it hasn't been updated in quite awhile, so updates will be relatively slow-going.  

1. When you pass in your list of dicts, you should only include the `y` and `z` parameters (`name`, `type`, .. shouldn't be added)
2. The extendData prop takes in 3 props `updateData, traceIndices, maxPoints`. If the variables aren't being assigned correctly, you might try explicitly defining the traces to update in your tuple: `return updateData, [1, 2]`

Any console log errors to share?

**Comment by nsbruce** [comment]
Thanks for the reply! The snippet above is what is used to create the graph initially.

1. The list of dicts I am passing does not contain `name` or `type`. The snippet above is what is used to build the graph initially but within the callback only y and z are dict members.
2. I am passing all three props as lists: 
```
updatedData = [dict(y=[newLine]), dict(z=[spec])]
traceIndices = [0,0]
maxPoints = [len(newLine), spec.shape[1]]
return updatedData, traceIndices, maxPoints
```

The error I get is:
```
dash.exceptions.InvalidCallbackReturnValue: Invalid number of output values for spec-waterfall.extendData
Expected 1, got 3
```

This isn't fixed by passing the return as a single list `return [updateData, traceIndices, maxPoints]` which gives the same error.

What DOES work is to break apart the subplot into two separate ExtendedGraph instances and use the extendData props on them separately.

```
updatedSpec = dict(y=[newLine]), [0], spec_width
updatedWaterfall = dict(z=[spec]), [0], waterfall_height
return updatedSpec, updatedWaterfall
```

This just means you can't share axes etc so I wanted to do this for subplots.

**Comment by bcliang** [comment]
I'm not really familiar with heatmaps, so if you can give me a full example to debug that might go a bit easier. 

My initial thought is that for any plotly figure (including when you use multiple subplots) assigns unique trace indices. So, even though you have 2 subplots, the traces are going to be traces 0 and 1 (not 0 and 0). You might only need to make a simple change `traceIndices = [0,1]`

Just as an example, I took the subplot example for `dcc.Graph` that is on the dash docs website and didn't have any issues extending two scatter ("line") traces that are on separate subplots. If plotly.js supports heatmaps with the `extendTraces()`, this component should work out of the box.

```python
from plotly.subplots import make_subplots
import dash_extendable_graph as deg
import dash
from dash.dependencies import Input, Output, State
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objects as go
import random

app = dash.Dash(__name__)

app.layout = html.Div([
    deg.ExtendableGraph(id="graph"),
    html.P("Subplots Width:"),
    dcc.Slider(
        id='slider-width', min=0, max=1, 
        value=0.5, step=0.01),
    dcc.Interval(
        id='interval_extendablegraph_update',
        interval=1000,
        n_intervals=0,
        max_intervals=20),
])

@app.callback(
    Output("graph", "figure"), 
    [Input("slider-width", "value")])
def customize_width(left_width):
    fig = make_subplots(
        rows=1, cols=2, 
        column_widths=[left_width, 1 - left_width])

    fig.add_trace(
        go.Scatter(x=[1, 2, 3], y=[4, 5, 6]),
        row=1, col=1)

    fig.add_trace(
        go.Scatter(x=[20, 30, 40], y=[50, 60, 70]),
        row=1, col=2)
    return fig

@app.callback(Output('graph', 'extendData'),
              [Input('interval_extendablegraph_update', 'n_intervals')],
              [State('graph', 'figure')])
def update_extend_first_n_traces(n_intervals, existing):
    if not existing:
        return dash.no_update
    
    x_new = existing['data'][0]['x'][-1] + 1
    return [dict(x=[x_new], y=[random.random()]), dict(x=[x_new], y=[random.random()])]

app.run_server(debug=True)
```
